# sudo: false --> run dist image in docker container on shared host for faster startup (runs slower)
# sudo: required --> run dist image in VM on Google Compute Engine for slower startup (runs faster)
sudo: required

language: android
jdk: oraclejdk8
dist: precise

#branches:
#  only:
#    - master

env:
  global:
    - ADB_INSTALL_TIMEOUT=10 # default is 2 minutes and sometimes is not enough
    - BUILD_TOOLS="27.0.3"
  matrix:
    - API_LEVEL=25 ABI="google_apis;arm64-v8a"
    - API_LEVEL=25 ABI="google_apis;armeabi-v7a"
    - API_LEVEL=24 ABI="google_apis;arm64-v8a"
    - API_LEVEL=24 ABI="google_apis;armeabi-v7a"
    - API_LEVEL=23 ABI="google_apis;armeabi-v7a"
    - API_LEVEL=21 ABI="default;armeabi-v7a"

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-$BUILD_TOOLS
    - android-$API
    - extra-android-m2repository
    - sys-img-$ABI-android-$API

before_install:
  # Avoid useless reupload of cache after every build, see https://docs.travis-ci.com/user/languages/android
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
  - yes | sdkmanager --update
  - yes | sdkmanager "system-images;android-$API_LEVEL;$ABI"
  - yes | sdkmanager "build-tools;"$BUILD_TOOLS
  # Accept licenses before installing components, no need to echo y for each component
  - yes | sdkmanager --licenses
  - sdkmanager --list
  - chmod +x gradlew

before_script:
  # Create and start emulator
  - echo no | avdmanager create avd -n testAVD -k "system-images;android-$API_LEVEL;$ABI"
  - $ANDROID_HOME/emulator/emulator -avd testAVD -no-skin -no-window &
  - android-wait-for-emulator
  - adb devices
  - adb shell input keyevent 82 &

script:
  - "./gradlew clean test"