# sudo: false --> run dist image in docker container on shared host for faster startup (runs slower)
# sudo: required --> run dist image in VM on Google Compute Engine for slower startup (runs faster)
sudo: required
language: android
jdk: oraclejdk8
dist: precise
env:
  global:
    - ADB_INSTALL_TIMEOUT=10 # default is 2 minutes and sometimes is not enough
    - BUILD_TOOLS="27.0.3"
  matrix:
    - API_LEVEL=25 ABI="google_apis;arm64-v8a"
    - API_LEVEL=25 ABI="google_apis;armeabi-v7a"

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-$BUILD_TOOLS
    - android-$API
    - extra-android-m2repository
    - sys-img-$ABI-android-$API

licenses:
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
    - 'android-sdk-preview-license-.+'

before_install:
  - touch /home/travis/.android/repositories.cfg
  - yes | sdkmanager --update
  - yes | sdkmanager "system-images;android-$API_LEVEL;$ABI"
  - yes | sdkmanager "build-tools;"$BUILD_TOOLS
  # Accept licenses before installing components, no need to echo y for each component
  - yes | sdkmanager --licenses
  - sdkmanager --list
  - chmod +x gradlew
  - "./gradlew dependencies || true"

before_script:
  # compile the code so gradle and dependencies are all downloaded
  - ./gradlew assembleDebug
  # Create and start emulator
  - echo no | avdmanager create avd -n testAVD -k "system-images;android-$API_LEVEL;$ABI"
  - $ANDROID_HOME/emulator/emulator -avd testAVD -no-skin -no-window &
  - android-wait-for-emulator
  - adb devices
  - adb shell input keyevent 82 &

script:
  - "./gradlew clean test"