language: android
jdk: oraclejdk8
sudo: required
dist: precise
env:
  global:
    - ADB_INSTALL_TIMEOUT=10 # default is 2 minutes and sometimes is not enough
  matrix:
    - API="system-images;android-21;google_apis;armeabi-v7a"

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-27.0.3
    - android-21
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-21

licenses:
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
    - 'android-sdk-preview-license-.+'

before_install:
  - touch /home/travis/.android/repositories.cfg
  - yes | sdkmanager --update
  - yes | sdkmanager $API
  - yes | sdkmanager "build-tools;27.0.3"
  - yes | sdkmanager --licenses
  - which avdmanager
  - sdkmanager --list
  - chmod +x gradlew
  - "./gradlew dependencies || true"

before_script:
  # compile the code so gradle and dependencies are all downloaded
  - ./gradlew assembleDebug
  # Create and start emulator
  - echo no | android create avd --force --name testAVD --package $API   #Create AVD for given api
  - emulator -avd testAVD -no-skin -no-window &
  - android-wait-for-emulator
  - adb devices
  - adb shell input keyevent 82 &
  - adb logcat -s TestRunner &

script: ./gradlew connectedCheck