language: android
jdk: oraclejdk8
sudo: false
env:
  matrix:
    - ANDROID_TARGET=android-21  ANDROID_ABI=armeabi-v7a
android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-27.0.3
    - android-21
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-21

licenses:
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
    - 'android-sdk-preview-license-.+'

before_install:
  - touch /home/travis/.android/repositories.cfg
  - yes | sdkmanager --update
  - yes | sdkmanager "system-images;$ANDROID_TARGET;google_apis;$ANDROID_ABI"
  - yes | sdkmanager "build-tools;27.0.3"
  - yes | sdkmanager --licenses
  - which avdmanager
  - sdkmanager --list
  - chmod +x gradlew
  - "./gradlew dependencies || true"

before_script:
  # compile the code so gradle and dependencies are all downloaded
  - ./gradlew assembleDebug
  # Create and start emulator
  - echo no | android create avd --force --name test --target "android-$ANDROID_TARGET" --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb devices
  - adb shell input keyevent 82 &
  - adb logcat -s TestRunner &

script: ./gradlew connectedCheck